/*
 * Copyright (c) 2011 Bartlomiej Siwek All rights reserved.
 */

#ifndef ELG_ENTITYMANAGER_ENTITYMANAGERPROFILING_H_
#define ELG_ENTITYMANAGER_ENTITYMANAGERPROFILING_H_

#include "Elg/Performance/ScopeProfiler.h"

#define ELG_PROFILE_ENTITY_MANAGER

#ifdef ELG_PROFILE_ENTITY_MANAGER
#define ELG_PROFILE_ENTITY_MANAGER_SCOPE ELG_PROFILE_SCOPE
#else  // ELG_PROFILE_ENTITY_MANAGER
#define ELG_PROFILE_ENTITY_MANAGER_SCOPE
#endif  // ELG_PROFILE_ENTITY_MANAGER

#endif  // ELG_ENTITYMANAGER_ENTITYMANAGERPROFILING_H_
