/*
 * Copyright (c) 2012 Bartlomiej Siwek All rights reserved.
 */

#ifndef TETRIS_SYSTEMS_USERINPUTSYSTEM_USERINPUTSYSTEMPROFILING_H_
#define TETRIS_SYSTEMS_USERINPUTSYSTEM_USERINPUTSYSTEMPROFILING_H_

#include "Elg/Performance/ScopeProfiler.h"

#define TETRIS_PROFILE_USERINPUTSYSTEM

#ifdef TETRIS_PROFILE_USERINPUTSYSTEM
#define TETRIS_PROFILE_USERINPUTSYSTEM_UPDATE ELG_PROFILE_NAMED_SCOPE("UserInputSystem::Update")
#else  // TETRIS_PROFILE_USERINPUTSYSTEM
#define TETRIS_PROFILE_USERINPUTSYSTEM_UPDATE
#endif  // TETRIS_PROFILE_USERINPUTSYSTEM

#endif  // TETRIS_SYSTEMS_USERINPUTSYSTEM_USERINPUTSYSTEMPROFILING_H_
