/*
 * Copyright (c) 2012 Bartlomiej Siwek All rights reserved.
 */

#ifndef TETRIS_SYSTEMS_GAMELOGICSYSTEM_GAMELOGICSYSTEMPROFILING_H_
#define TETRIS_SYSTEMS_GAMELOGICSYSTEM_GAMELOGICSYSTEMPROFILING_H_

#include "Elg/Performance/ScopeProfiler.h"

#define TETRIS_PROFILE_GAMELOGICSYSTEM

#ifdef TETRIS_PROFILE_GAMELOGICSYSTEM
#define TETRIS_PROFILE_GAMELOGICSYSTEM_UPDATE ELG_PROFILE_NAMED_SCOPE("GameLogicSystem::Update")
#else  // TETRIS_PROFILE_GAMELOGICSYSTEM
#define TETRIS_PROFILE_GAMELOGICSYSTEM_UPDATE
#endif  // TETRIS_PROFILE_GAMELOGICSYSTEM

#endif  // TETRIS_SYSTEMS_GAMELOGICSYSTEM_GAMELOGICSYSTEMPROFILING_H_
