/*
 * Copyright (c) 2012 Bartlomiej Siwek All rights reserved.
 */

#ifndef TETRIS_SYSTEMS_GRAPHICSSYSTEM_GRAPHICSSYSTEMPROFILING_H_
#define TETRIS_SYSTEMS_GRAPHICSSYSTEM_GRAPHICSSYSTEMPROFILING_H_

#include "Elg/Performance/ScopeProfiler.h"

#define TETRIS_PROFILE_GRAPHICSSYSTEM

#ifdef TETRIS_PROFILE_GRAPHICSSYSTEM
#define TETRIS_PROFILE_GRAPHICSSYSTEM_RENDER ELG_PROFILE_NAMED_SCOPE("GraphicsSystem::Render")
#else  // TETRIS_PROFILE_GRAPHICSSYSTEM
#define TETRIS_PROFILE_GRAPHICSSYSTEM_RENDER
#endif  // TETRIS_PROFILE_GRAPHICSSYSTEM

#endif  // TETRIS_SYSTEMS_GRAPHICSSYSTEM_GRAPHICSSYSTEMPROFILING_H_
